#pragma once;

#define HARDWARE_TEST_PATH "cd /home/ubuntu/hardware_test/ \n"
#define UPGRADE_SH "/home/ubuntu/hardware_test/0_copy_Image.sh\n"
#define STREAM_LED "/home/ubuntu/hardware_test/28_Test_single_led_python.sh\n"
#define ALL_LED "/home/ubuntu/hardware_test/3_led_python.sh\n"
#define LED_WARM "/home/ubuntu/hardware_test/19_LED_warm_python.sh\n"
#define LED_COOL "/home/ubuntu/hardware_test/20_LED_cool_python.sh\n"
#define LED_OFF "/home/ubuntu/hardware_test/21_LED_off_python.sh\n"
#define LED_RGB_RED "/home/ubuntu/hardware_test/16_RGB_red_python.sh\n"
#define LED_RGB_GREEN "/home/ubuntu/hardware_test/17_RGB_green_python.sh\n"
#define LED_RGB_BLUE "/home/ubuntu/hardware_test/18_RGB_blue_python.sh\n"
#define LED_RGB_OFF "/home/ubuntu/hardware_test/63_closergb_python.sh\n"
#define SAVE_RAW_IMAGE_0 "/home/ubuntu/hardware_test/30_save_raw_image_0.sh\n"
#define SAVE_RAW_IMAGE_1 "/home/ubuntu/hardware_test/31_save_raw_image_1.sh\n"
#define SAVE_RAW_IMAGE_2 "/home/ubuntu/hardware_test/32_save_raw_image_2.sh\n"
#define SAVE_RAW_IMAGE_3 "/home/ubuntu/hardware_test/33_save_raw_image_3.sh\n"
#define Play_Camera_0 "/home/ubuntu/hardware_test/54_Play_Camera_0.sh\n"
#define Play_Camera_1 "/home/ubuntu/hardware_test/55_Play_Camera_1.sh\n"
#define Play_Camera_2 "/home/ubuntu/hardware_test/56_Play_Camera_2.sh\n"
#define Play_Camera_3 "/home/ubuntu/hardware_test/57_Play_Camera_3.sh\n"
#define STITCH_LIVE "/home/ubuntu/hardware_test/62_stitch_live.sh\n"
#define UART1_TEST "/home/ubuntu/hardware_test/12_stm32_uart1.sh\n"
#define UART2_TEST "/home/ubuntu/hardware_test/13_stm32_uart2.sh\n"
#define STOP_STREAM_LED "/home/ubuntu/hardware_test/65_kill_led_single_test.sh"
#define PLAY_AUDIO "/home/ubuntu/hardware_test/2_audio.sh \n"
#define PLAY_LEFT_CHANNEL "/home/ubuntu/hardware_test/14_speaker_left_channel.sh\n"
#define PLAY_RIGHT_CHANNEL "/home/ubuntu/hardware_test/15_speaker_right_channel.sh\n"
#define RECORD "/home/ubuntu/hardware_test/4_record.sh\n"
#define MOTOR_CONTROL "/home/ubuntu/hardware_test/11_motor.sh\n"
#define MOTOR_AUTO  "/home/ubuntu/hardware_test/38_motor_auto.sh\n"
#define MOTOR_AUDO_STOP "/home/ubuntu/hardware_test/39_motor_stop.sh\n"
#define SOUND_MAX "/home/ubuntu/hardware_test/37_sound_max.sh\n"
#define ATT_MOTOR "/home/ubuntu/hardware_test/8_attmotor.sh\n"
#define LIGHT_SENSOR "/home/ubuntu/hardware_test/6_lightsensor.sh\n"
#define DISTANCE_TEST "/home/ubuntu/hardware_test/5_distance.sh\n"
#define GAS_MOTOR "/home/ubuntu/hardware_test/10_gasmotor.sh\n"
#define FAN_SET_9000 "/home/ubuntu/hardware_test/58_fan_set_9000_speed_python.sh\n"
#define FAN_SET_4000 "/home/ubuntu/hardware_test/46_fan_set_4000_speed_python.sh\n"
#define GET_PRESSURE "/home/ubuntu/hardware_test/27_getpressure.sh\n"
#define TEST_PIR "/home/ubuntu/hardware_test/22_test_pir.sh\n"

//#define HARDWARE_TEST_PATH_28 "cd /home/nvidia/hardware_test/ \n"
#define HARDWARE_TEST_PATH_28 "cd /home/nvidia/rabbit_tool/ \n"
#define UPGRADE_SH_28 "/home/nvidia/hardware_test/0_copy_Image.sh\n"
#define STREAM_LED_28 "/home/nvidia/hardware_test/28_Test_single_led_python.sh\n"
#define ALL_LED_28 "/home/nvidia/hardware_test/3_led_python.sh\n"
#define LED_WARM_28 "/home/nvidia/hardware_test/19_LED_warm_python.sh\n"
#define LED_COOL_28 "/home/nvidia/hardware_test/20_LED_cool_python.sh\n"
#define LED_OFF_28 "/home/nvidia/hardware_test/21_LED_off_python.sh\n"
#define LED_RGB_RED_28 "/home/nvidia/hardware_test/16_RGB_red_python.sh\n"
#define LED_RGB_GREEN_28 "/home/nvidia/hardware_test/17_RGB_green_python.sh\n"
#define LED_RGB_BLUE_28 "/home/nvidia/hardware_test/18_RGB_blue_python.sh\n"
#define LED_RGB_OFF_28 "/home/nvidia/hardware_test/63_closergb_python.sh\n"
#define SAVE_RAW_IMAGE_0_28 "/home/nvidia/hardware_test/30_save_raw_image_0.sh\n"
#define SAVE_RAW_IMAGE_1_28 "/home/nvidia/hardware_test/31_save_raw_image_1.sh\n"
#define SAVE_RAW_IMAGE_2_28 "/home/nvidia/hardware_test/32_save_raw_image_2.sh\n"
#define SAVE_RAW_IMAGE_3_28 "/home/nvidia/hardware_test/33_save_raw_image_3.sh\n"
#define Play_Camera_0_28 "/home/nvidia/hardware_test/54_Play_Camera_0.sh\n"
#define Play_Camera_1_28 "/home/nvidia/hardware_test/55_Play_Camera_1.sh\n"
#define Play_Camera_2_28 "/home/nvidia/hardware_test/56_Play_Camera_2.sh\n"
#define Play_Camera_3_28 "/home/nvidia/hardware_test/57_Play_Camera_3.sh\n"
#define STITCH_LIVE_28 "/home/nvidia/hardware_test/62_stitch_live.sh\n"
#define UART1_TEST_28 "/home/nvidia/hardware_test/12_stm32_uart1.sh\n"
#define UART2_TEST_28 "/home/nvidia/hardware_test/13_stm32_uart2.sh\n"
#define STOP_STREAM_LED_28 "/home/nvidia/hardware_test/65_kill_led_single_test.sh"
#define PLAY_AUDIO_28 "/home/nvidia/hardware_test/2_audio.sh \n"
#define PLAY_LEFT_CHANNEL_28 "/home/nvidia/hardware_test/14_speaker_left_channel.sh\n"
#define PLAY_RIGHT_CHANNEL_28 "/home/nvidia/hardware_test/15_speaker_right_channel.sh\n"
#define RECORD_28 "/home/nvidia/hardware_test/4_record.sh\n"
#define MOTOR_CONTROL_28 "/home/nvidia/hardware_test/11_motor.sh\n"
#define MOTOR_AUTO_28  "/home/nvidia/hardware_test/38_motor_auto.sh\n"
#define MOTOR_AUDO_STOP_28 "/home/nvidia/hardware_test/39_motor_stop.sh\n"
#define SOUND_MAX_28 "/home/nvidia/hardware_test/37_sound_max.sh\n"
#define ATT_MOTOR_28 "/home/nvidia/hardware_test/8_attmotor.sh\n"
#define LIGHT_SENSOR_28 "/home/nvidia/hardware_test/6_lightsensor.sh\n"
#define DISTANCE_TEST_28 "/home/nvidia/hardware_test/5_distance.sh\n"
#define GAS_MOTOR_28 "/home/nvidia/hardware_test/10_gasmotor.sh\n"
#define FAN_SET_9000_28 "/home/nvidia/hardware_test/58_fan_set_9000_speed_python.sh\n"
#define FAN_SET_4000_28 "/home/nvidia/hardware_test/46_fan_set_4000_speed_python.sh\n"
#define GET_PRESSURE_28 "/home/nvidia/hardware_test/27_getpressure.sh\n"
//#define TEST_PIR_28 "/home/nvidia/hardware_test/22_test_pir.sh\n"
#define TEST_PIR_28 "/home/nvidia/rabbit_tool/get_pir.sh\n"
